#!/usr/bin/env sh
set -eu

_program_name="$(basename "${0}")"
_version="1.0.0"

usage() {
	cat <<-EOF
		Automatically designs a consensus protein from a FASTA file.

		Usage: ${_program_name} [-h|V] | [-v] [-w[=| ]<WORK_DIR>] [-d[=| ]<OUTPUT_DIR>] [-o[=| ]<OUTPUT_FASTA>] [-t[=| ]<THREAD_LIMIT>] [-m[=| ]<MEMORY_LIMIT>] [-g[=| ]<GAP_THRESHOLD>] [-l[=| ]<LENGTH_THRESHOLD>] <INPUT_FASTA>

		Options:
		  -h, --help                                 Show this help message and exit.
		  -V, --version                              Show version information and exit.
		  -v, --verbose                              Enable debug logging.
		  -w, --working-directory <WORK_DIR>         The directory in which to create completion logs and intermediary files.
		  -d, --output-directory <OUTPUT_DIR>        The directory in which to output consensus proteins.
		  -o, --output-file <OUTPUT_FASTA>           Output consensus protein filename. Defaults to <INPUT_FILE>_consensus.fasta
		  -g, --gap-threshold <GAP_THRESHOLD>        Gap frequecy threshold used to define a consensus position. Defaults to 0.5, removing positions with higher gap frequency. Must be a value between 0 and 1.
		  -l, --length-threshold <LENGTH_THRESHOLD>  Sequence length filtering threshold value. Defaults to 0.3, removing sequences that deviate +/- 30% from median sequence length of set. Must be a value between 0 and 1.
		  -t, --thread-limit <THREAD_LIMIT>          The maximum number of threads to use for alignment. Defaults to 1.
		  -m, --memory-limit <MEMORY_LIMIT>          The maximum amount of memory to use for clustering, in megabytes. Defaults to 2000.
		  -p, --parallelism <PARALLELISM>            The maximum number of input files to process simultaneously, if receiving a directory as input. Defaults to the number of available CPU cores.
		      --                                     Stop processing command line arguments.

		Positional Arguments:
		  <INPUT_FASTA>                              An input file in FASTA format, optionally compressed via gzip. Alternatively, a directory of such files.

		Examples:
		  ${_program_name} --memory-limit 2000 --thread-limit 24 --gap-threshold 0.3 -l 0.25 example.fasta --output-file consensus.fasta
		  ${_program_name} --parallelism 32 --thread-limit 2 --output-file consensus_proteome.fasta --output-directory /data -- my_directory_of_fasta_files
		  ${_program_name} -w "\$(mktemp -d)" -M 1000 -t 64 example.fasta --output-file consensus.fasta
	EOF
}

version() {
	cat <<-EOF
		Loom ${_version}
		Copyright (C) 2026 Josh Beale <jbeale2023@gmail.com>.
		License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
		This is free software: you are free to change and redistribute it.
		There is NO WARRANTY, to the extent permitted by law.
	EOF
}

log() {
	printf "%s %s %s\n" "$(date +'%Y%M%D %H:%M:%S')" "${_program_name}" "${1}" >&2
}

throw() {
	log "${1}"
	exit 1
}

setup() {
	[ "${verbose}" -eq 1 ] && log "DEBUG: Checking dependencies."
	command -v length_filter >/dev/null 2>&1 || throw "ERROR: Unable to find length_filter command."
	command -v cd-hit >/dev/null 2>&1 || throw "ERROR: Unable to find cd-hit command."
	command -v mafft >/dev/null 2>&1 || throw "ERROR: Unable to find mafft command."
	command -v build_consensus >/dev/null 2>&1 || throw "ERROR: Unable to find build_consensus command."

	[ "${verbose}" -eq 1 ] && log "DEBUG: Creating output directory."
	mkdir -p "${output_dir}" || throw "ERROR: Unable to create output directory."

	[ "${verbose}" -eq 1 ] && log "DEBUG: Creating working directory."
	mkdir -p "${work_dir}" || throw "ERROR: Unable to create working directory."

	[ "${verbose}" -eq 1 ] && log "DEBUG: Creating completion logs."
	mkdir -p "${log_dir}" || throw "ERROR: Unable to create completion log directory."
	touch "${length_filtered_log}" || throw "ERROR: Unable to create completion log for length filtering."
	touch "${clustered_log}" || throw "ERROR: Unable to create completion log for clustering."
	touch "${aligned_log}" || throw "ERROR: Unable to create completion log for alignments."
	touch "${completed_log}" || throw "ERROR: Unable to create completion log for consensus building."
}

decompress_input_file() {
	command -v gzip >/dev/null 2>&1 || throw "ERROR: gzip must be installed to process gzipped input files."
	gunzipped="${work_dir}/$(basename "${1%.fa*}").fasta"
	gzip -dfck "${input_file}" >"${gunzipped}" || throw "$(printf "ERROR: Failed to decompress input file %s. Is it in gz format?" "${input_file}")"
	printf "%s" "${gunzipped}"
}

validate_input() {
	[ "${verbose}" -eq 1 ] && log "Validating input file."
	input_file="${1}"

	# Validate that the input file exists
	[ -f "${input_file}" ] || throw "$(printf "ERROR: Input file %s does not exist." "${input_file}")"

	# Decompress any valid .gz, .Z, or .tar.gz file
	if printf "%s\n" "${input_file}" | grep -qE -- "([\.\-][gG][zZ])|([\.\-_][zZ])|([\.\-][tT][aAgG][zZ])|" >/dev/null 2>&1; then
		input_file="$(decompress_input_file "${input_file}")"
	fi

	# Validate that the input file is in fasta format and contains at least one sequence
	grep -qE -- "^>" "${input_file}" || throw "$(printf "ERROR: Input file %s is not in FASTA format." "${input_file}")"
	grep -qE -- "^[^>]" "${input_file}" || throw "$(printf "ERROR: Input FASTA %s file contains no sequences." "${input_file}")"

	printf "%s" "${input_file}"
}

main() {
	# Debug logging control, set to 1 to enable
	verbose="0"
	# Output and logging paths
	output_dir="."
	log_dir="${output_dir}/logs"
	length_filtered_log="${log_dir}/length_filtered.log"
	clustered_log="${log_dir}/clustered.log"
	aligned_log="${log_dir}/aligned.log"
	completed_log="${log_dir}/completed.log"

	# Setting the working directory to "$(mktemp -d)" if it is backed by an in-memory
	# tempfs will often yield better performance, but will substantially increase
	# memory consumption and increase the difficulty of resuming an interrupted run.
	work_dir="${output_dir}/work"
}

main "${@}"
