#!/usr/bin/env sh
set -eu

_program_name="$(basename "${0}")"
_version="1.0.0_beta"

usage() {
	cat <<-EOF
		Automatically designs a consensus protein from a FASTA file.

		Usage: ${_program_name} [-h|V] | [-v] [-w[=| ]<WORK_DIR>] [-d[=| ]<OUTPUT_DIR>] [-o[=| ]<OUTPUT_FASTA>] [-t[=| ]<THREAD_LIMIT>] [-m[=| ]<MEMORY_LIMIT>] [-i[=| ]<IDENTITY_THRESHOLD>] [-g[=| ]<GAP_THRESHOLD>] [-l[=| ]<LENGTH_THRESHOLD>] <INPUT_FASTA>

		Options:
		  -h, --help                                     Show this help message and exit.
		  -V, --version                                  Show version information and exit.
		  -v, --verbose                                  Enable debug logging.
		  -w, --working-directory <WORK_DIR>             The directory in which to create completion logs and intermediary files.
		  -d, --output-directory <OUTPUT_DIR>            The directory in which to output consensus proteins. Defaults to ./output
		  -o, --output-file <OUTPUT_FASTA>               Output consensus protein filename. Defaults to <INPUT_FILE>_consensus.fasta
		  -i, --identity-threshold <IDENTITY_THRESHOLD>  Sequence identity threshold used to remove sequences during clustering. Defaults to 0.9.
		  -g, --gap-threshold <GAP_THRESHOLD>            Gap frequecy threshold used to define a consensus position. Defaults to 0.5, removing positions with higher gap frequency. Must be a value between 0 and 1.
		  -l, --length-threshold <LENGTH_THRESHOLD>      Sequence length filtering threshold value. Defaults to 0.3, removing sequences that deviate +/- 30% from median sequence length of set. Must be a value between 0 and 1.
		  -t, --thread-limit <THREAD_LIMIT>              The maximum number of threads to use for alignment. Defaults to 1.
		  -m, --memory-limit <MEMORY_LIMIT>              The maximum amount of memory to use for clustering, in megabytes. Defaults to 4000.
		  -p, --parallelism <PARALLELISM>                The maximum number of input files to process simultaneously, if receiving a directory as input. Defaults to the number of available CPU cores.
		      --                                         Stop processing command line arguments.

		Positional Arguments:
		  <INPUT_FASTA>                                  An input file in FASTA format, optionally compressed via gzip. Alternatively, a directory of such files.

		Examples:
		  ${_program_name} --memory-limit 2000 --thread-limit 24 --gap-threshold 0.3 -l 0.25 example.fasta --output-file consensus.fasta

		  ${_program_name} --parallelism 32 --thread-limit 2 --output-file consensus_proteome.fasta --output-directory /data -- my_directory_of_fasta_files

		  ${_program_name} -w "\$(mktemp -d)" -M 1000 -t 64 example.fasta --output-file consensus.fasta
	EOF
}

version() {
	cat <<-EOF
		Loom ${_version}
		Copyright (C) 2026 Josh Beale <jbeale2023@gmail.com>.
		License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
		This is free software: you are free to change and redistribute it.
		There is NO WARRANTY, to the extent permitted by law.
	EOF
}

log() {
	printf "%s %s %s\n" "$(date +'%Y%M%D %H:%M:%S')" "${_program_name}" "${1}" >&2
}

throw() {
	log "${1}"
	exit 1
}

setup() {
	[ "${verbose}" -eq 1 ] && log "DEBUG: Checking dependencies."
	command -v length_filter >/dev/null 2>&1 || throw "ERROR: Unable to find length_filter command."
	command -v cd-hit >/dev/null 2>&1 || throw "ERROR: Unable to find cd-hit command."
	command -v mafft >/dev/null 2>&1 || throw "ERROR: Unable to find mafft command."
	command -v build_consensus >/dev/null 2>&1 || throw "ERROR: Unable to find build_consensus command."

	[ "${verbose}" -eq 1 ] && log "DEBUG: Creating output directory."
	mkdir -p "${output_dir}" || throw "ERROR: Unable to create output directory."

	[ "${verbose}" -eq 1 ] && log "DEBUG: Creating working directory."
	mkdir -p "${work_dir}" || throw "ERROR: Unable to create working directory."

	[ "${verbose}" -eq 1 ] && log "DEBUG: Creating completion logs."
	mkdir -p "${log_dir}" || throw "ERROR: Unable to create completion log directory."
	touch "${length_filtered_log}" || throw "ERROR: Unable to create completion log for length filtering."
	touch "${clustered_log}" || throw "ERROR: Unable to create completion log for clustering."
	touch "${aligned_log}" || throw "ERROR: Unable to create completion log for alignments."
	touch "${completed_log}" || throw "ERROR: Unable to create completion log for consensus building."
}

decompress_input_file() {
	command -v gzip >/dev/null 2>&1 || throw "ERROR: gzip must be installed to process gzipped input files."
	gunzipped="${work_dir}/$(basename "${1%.fa*}").fasta"
	gzip -dfck "${input_file}" >"${gunzipped}" || throw "$(printf "ERROR: Failed to decompress input file %s. Is it in gz format?" "${input_file}")"
	printf "%s" "${gunzipped}"
}

validate_input() {
	[ "${verbose}" -eq 1 ] && log "Validating input file."
	input_file="${1}"

	# Validate that the input file exists
	[ -f "${input_file}" ] || throw "$(printf "ERROR: Input file %s does not exist." "${input_file}")"

	# Decompress any valid .gz, .Z, or .tar.gz file
	if printf "%s\n" "${input_file}" | grep -qE -- "([\.\-][gG][zZ])|([\.\-_][zZ])|([\.\-][tT][aAgG][zZ])" >/dev/null 2>&1; then
		input_file="$(decompress_input_file "${input_file}")"
	fi

	# Validate that the input file is in fasta format and contains at least one sequence
	grep -qE -- "^>" "${input_file}" || throw "$(printf "ERROR: Input file %s is not in FASTA format." "${input_file}")"
	grep -qE -- "^[^>]" "${input_file}" || throw "$(printf "ERROR: Input FASTA %s file contains no sequences." "${input_file}")"

	printf "%s" "${input_file}"
}

process_fasta() {
	# Validate that the input file is in fasta format and decompress it if necessary
	input_fasta="$(validate_input "${1}")"

	# Generate fasta stem for logging and paths for intermediary files
	fasta_stem="$(basename "${1%.fa*}")"
	output_fasta="${output_dir}/${output_fasta:-"${fasta_stem}.consensus"}"
	length_filtered="${work_dir}/${fasta_stem}.lf"
	clustered="${work_dir}/${fasta_stem}.cl"
	aligned="${work_dir}/${fasta_stem}.al"

	# Run loom pipeline, skipping already completed steps
	if ! grep -q -- "${fasta_stem}" "${length_filtered_log}" >/dev/null 2>&1; then
		[ "${verbose}" -eq 1 ] && log "$(printf "DEBUG: Length filtering %s." "${input_fasta}")"
		length_filter --threshold "${length_threshold}" --input "${input_fasta}" --output "${length_filtered}" --log "${log_dir}/${fasta_stem}_lf.log" && printf "%s\n" "${fasta_stem}" >>"${length_filtered_log}"
	fi
	grep -q -- "${fasta_stem}" "${length_filtered_log}" >/dev/null 2>&1 || throw "$(printf "ERROR: Failed to length filter input file: '%s'." "${input_fasta}")"

	if ! grep -q -- "${fasta_stem}" "${clustered_log}" >/dev/null 2>&1; then
		[ "${verbose}" -eq 1 ] && log "$(printf "DEBUG: Clustering %s." "${input_fasta}")"
		cd-hit -c "${identity_threshold}" -i "${length_filtered}" -M "${memory_limit}" -o "${clustered}" >/dev/null 2>&1 && printf "%s\n" "${fasta_stem}" >>"${clustered_log}"
	fi
	grep -q -- "${fasta_stem}" "${clustered_log}" >/dev/null 2>&1 || throw "$(printf "ERROR: Failed to cluster input file: '%s'." "${input_fasta}")"

	if ! grep -q -- "${fasta_stem}" "${aligned_log}" >/dev/null 2>&1; then
		[ "${verbose}" -eq 1 ] && log "$(printf "DEBUG: Aligning %s." "${input_fasta}")"
		mafft --quiet --auto --thread "${thread_limit}" "${clustered}" >"${aligned}" 2>/dev/null && printf "%s\n" "${fasta_stem}" >>"${aligned_log}"
	fi
	grep -q -- "${fasta_stem}" "${aligned_log}" >/dev/null 2>&1 || throw "$(printf "ERROR: Failed to align input file: '%s'." "${input_fasta}")"

	if ! grep -q -- "${fasta_stem}" "${completed_log}" >/dev/null 2>&1; then
		[ "${verbose}" -eq 1 ] && log "$(printf "DEBUG: Building consensus for %s." "${input_fasta}")"
		build_consensus --threshold "${gap_threshold}" --input "${aligned}" --output "${output_fasta}" --log "${log_dir}/${fasta_stem}_consensus.log" && printf "%s\n" "${fasta_stem}" >>"${completed_log}"
	fi
	grep -q -- "${fasta_stem}" "${completed_log}" >/dev/null 2>&1 || throw "$(printf "ERROR: Failed to build consensus for input file: '%s'." "${input_fasta}")"

	[ "${verbose}" -eq 1 ] && log "$(printf "DEBUG: Completed consensus for %s." "${input_fasta}")"
}

cull_workers() {
	for job in $dispatched_jobs; do
		kill "${job}" 2>/dev/null
	done
}

pipeline_completion() {
	cat <<-EOF >"${versions}"
		---
		  loom: "${_version}"
		  python: $(python --version | sed 's/Python //g')
		  numpy: $(python -c "import numpy; print(numpy.__version__)")
		  cd-hit: $(cd-hit --help | sed -n -e 's/^.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/p')
		  mafft: $(mafft --version 2>&1 | sed -n -e 's/^.*\([0-9]\+\.[0-9]\+\.\?[0-9]\+\?\).*$/\1/p')
	EOF
}

main() {
	# Parse Options
	while [ "${#}" -gt 0 ]; do
		if printf "%s" "${1}" | grep -q -E -- "^(-h)|(--h(e(l(p)?)?)?)" 2>/dev/null; then
			usage
			shift 1
			return 0
		elif printf "%s" "${1}" | grep -q -E -- "^(-V)|(--vers(i(o(n)?)?)?)" 2>/dev/null; then
			version
			shift 1
			return 0
		elif printf "%s" "${1}" | grep -q -E -- "^(-v)|(--verb(o(s(e)?)?)?)" 2>/dev/null; then
			verbose=1
			shift 1
		elif printf "%s" "${1}" | grep -q -E -- "^-v[wdoigltmp]" 2>/dev/null; then
			verbose=1
			case "${1}" in
			-vw*)
				case "${1}" in
				*=*)
					leader="${1%%=*}="
					work_dir="${1#"${leader}"}"
					;;
				-vw*)
					work_dir="${1#-vw}"
					;;
				*)
					throw "$(printf "ERROR: Invalid work directory format -- '%s'" "${1}")"
					;;
				esac
				if [ -z "${work_dir}" ]; then
					if [ -z "${2}" ]; then
						throw "ERROR: If --work-directory is specified, a work directory must be provided."
					fi
					case "${2}" in
					-*)
						throw "ERROR: If --work-directory is specified, a work directory must be provided."
						;;
					*)
						work_dir="${2}"
						shift 1
						;;
					esac
				fi
				;;
			-vd*)
				case "${1}" in
				*=*)
					leader="${1%%=*}="
					output_dir="${1#"${leader}"}"
					;;
				-vd*)
					output_dir="${1#-vw}"
					;;
				*)
					throw "$(printf "ERROR: Invalid output directory format -- '%s'" "${1}")"
					;;
				esac
				if [ -z "${output_dir}" ]; then
					if [ -z "${2}" ]; then
						throw "ERROR: If --output-directory is specified, an output directory must be provided."
					fi
					case "${2}" in
					-*)
						throw "ERROR: If --output-directory is specified, an output directory must be provided."
						;;
					*)
						output_dir="${2}"
						shift 1
						;;
					esac
				fi
				;;
			-vo*)
				case "${1}" in
				*=*)
					leader="${1%%=*}="
					output_fasta="${1#"${leader}"}"
					;;
				-vo*)
					output_fasta="${1#-vw}"
					;;
				*)
					throw "$(printf "ERROR: Invalid output file format -- '%s'" "${1}")"
					;;
				esac
				if [ -z "${output_fasta}" ]; then
					if [ -z "${2}" ]; then
						throw "ERROR: If --output-file is specified, an output file must be provided."
					fi
					case "${2}" in
					-*)
						throw "ERROR: If --output-file is specified, an output file must be provided."
						;;
					*)
						output_fasta="${2}"
						shift 1
						;;
					esac
				fi
				;;
			*) ;;
			esac
			shift 1
		elif printf "%s" "${1}" | grep -q -E -- "^(-w)|(--w(o(r(k(-(d(i(r(e(c(t(o(r(y)?)?)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				work_dir="${1#"${leader}"}"
				;;
			--work-directory*)
				work_dir="${1#--work-directory}"
				;;
			--work-director*)
				work_dir="${1#--work-director}"
				;;
			--work-directo*)
				work_dir="${1#--work-directo}"
				;;
			--work-direct*)
				work_dir="${1#--work-direct}"
				;;
			--work-direc*)
				work_dir="${1#--work-direc}"
				;;
			--work-dire*)
				work_dir="${1#--work-dire}"
				;;
			--work-dir*)
				work_dir="${1#--work-dir}"
				;;
			--work-di*)
				work_dir="${1#--work-di}"
				;;
			--work-d*)
				work_dir="${1#--work-d}"
				;;
			--work-*)
				work_dir="${1#--work-}"
				;;
			--work*)
				work_dir="${1#--work}"
				;;
			--wor*)
				work_dir="${1#--wor}"
				;;
			--wo*)
				work_dir="${1#--wo}"
				;;
			--w*)
				work_dir="${1#--w}"
				;;
			-w*)
				work_dir="${1#-w}"
				;;
			*)
				throw "$(printf "ERROR: Invalid work directory format -- '%s'" "${1}")"
				;;
			esac
			if [ -z "${work_dir}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --work-directory is specified, a work directory must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --work-directory is specified, a work directory must be provided."
					;;
				*)
					work_dir="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
		elif printf "%s" "${1}" | grep -q -E -- "^(-d)|(--output-d(i(r(e(c(t(o(r(y)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				output_dir="${1#"${leader}"}"
				;;
			--output-directory*)
				output_dir="${1#--output-directory}"
				;;
			--output-director*)
				output_dir="${1#--output-director}"
				;;
			--output-directo*)
				output_dir="${1#--output-directo}"
				;;
			--output-direct*)
				output_dir="${1#--output-direct}"
				;;
			--output-direc*)
				output_dir="${1#--output-direc}"
				;;
			--output-dire*)
				output_dir="${1#--output-dire}"
				;;
			--output-dir*)
				output_dir="${1#--output-dir}"
				;;
			--output-di*)
				output_dir="${1#--output-di}"
				;;
			--output-d*)
				output_dir="${1#--output-d}"
				;;
			-d*)
				output_dir="${1#-d}"
				;;
			*)
				throw "$(printf "ERROR: Invalid output directory format -- '%s'" "${1}")"
				;;
			esac
			if [ -z "${output_dir}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --output-directory is specified, an output directory must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --output-directory is specified, an output directory must be provided."
					;;
				*)
					output_dir="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
		elif printf "%s" "${1}" | grep -q -E -- "^(-o)|(--output-f(i(l(e)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				output_fasta="${1#"${leader}"}"
				;;
			--output-file*)
				output_fasta="${1#--output-file}"
				;;
			--output-fil*)
				output_fasta="${1#--output-fil}"
				;;
			--output-fi*)
				output_fasta="${1#--output-fi}"
				;;
			--output-f*)
				output_fasta="${1#--output-f}"
				;;
			-o*)
				output_fasta="${1#-o}"
				;;
			*)
				throw "$(printf "ERROR: Invalid output file format -- '%s'" "${1}")"
				;;
			esac
			if [ -z "${output_fasta}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --output-file is specified, an output file must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --output-file is specified, an output file must be provided."
					;;
				*)
					output_fasta="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
		elif printf "%s" "${1}" | grep -q -E -- "^(-i)|(--i(d(e(n(t(i(t(y(-(t(h(r(e(s(h(o(l(d)?)?)?)?)?)?)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				identity_threshold="${1#"${leader}"}"
				;;
			--identity-threshold*)
				identity_threshold="${1#--identity-threshold}"
				;;
			--identity-threshol*)
				identity_threshold="${1#--identity-threshol}"
				;;
			--identity-thresho*)
				identity_threshold="${1#--identity-thresho}"
				;;
			--identity-thresh*)
				identity_threshold="${1#--identity-thresh}"
				;;
			--identity-thres*)
				identity_threshold="${1#--identity-thres}"
				;;
			--identity-thre*)
				identity_threshold="${1#--identity-thre}"
				;;
			--identity-thr*)
				identity_threshold="${1#--identity-thr}"
				;;
			--identity-th*)
				identity_threshold="${1#--identity-th}"
				;;
			--identity-t*)
				identity_threshold="${1#--identity-t}"
				;;
			--identity-*)
				identity_threshold="${1#--identity-}"
				;;
			--identity*)
				identity_threshold="${1#--identity}"
				;;
			--identit*)
				identity_threshold="${1#--identit}"
				;;
			--identi*)
				identity_threshold="${1#--identi}"
				;;
			--ident*)
				identity_threshold="${1#--ident}"
				;;
			--iden*)
				identity_threshold="${1#--iden}"
				;;
			--ide*)
				identity_threshold="${1#--ide}"
				;;
			--id*)
				identity_threshold="${1#--id}"
				;;
			--i*)
				identity_threshold="${1#--i}"
				;;
			-i*)
				identity_threshold="${1#-i}"
				;;
			*)
				throw "$(printf "ERROR: Invalid identity threshold format -- '%s'. Please specify a decimal value between 0 and 1." "${1}")"
				;;
			esac
			if [ -z "${identity_threshold}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --identity-threshold is specified, a decimal threshold between 0 and 1 must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --identity-threshold is specified, a decimal threshold between 0 and 1 must be provided."
					;;
				*)
					identity_threshold="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
			awk -v number="${identity_threshold}" 'END { exit !( number !~ /[^0-9.]/ && number !~ /\..*\./ && number >= 0 && number <= 1) }' /dev/null || throw "$(printf "ERROR: Invalid identity threshold format -- '%s'. Please specify a decimal value between 0 and 1." "${identity_threshold}")"
		elif printf "%s" "${1}" | grep -q -E -- "^(-g)|(--g(a(p(-(t(h(r(e(s(h(o(l(d)?)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				gap_threshold="${1#"${leader}"}"
				;;
			--gap-threshold*)
				gap_threshold="${1#--gap-threshold}"
				;;
			--gap-threshol*)
				gap_threshold="${1#--gap-threshol}"
				;;
			--gap-thresho*)
				gap_threshold="${1#--gap-thresho}"
				;;
			--gap-thresh*)
				gap_threshold="${1#--gap-thresh}"
				;;
			--gap-thres*)
				gap_threshold="${1#--gap-thres}"
				;;
			--gap-thre*)
				gap_threshold="${1#--gap-thre}"
				;;
			--gap-thr*)
				gap_threshold="${1#--gap-thr}"
				;;
			--gap-th*)
				gap_threshold="${1#--gap-th}"
				;;
			--gap-t*)
				gap_threshold="${1#--gap-t}"
				;;
			--gap-*)
				gap_threshold="${1#--gap-}"
				;;
			--gap*)
				gap_threshold="${1#--gap}"
				;;
			--ga*)
				gap_threshold="${1#--ga}"
				;;
			--g*)
				gap_threshold="${1#--g}"
				;;
			-g*)
				gap_threshold="${1#-g}"
				;;
			*)
				throw "$(printf "ERROR: Invalid gap threshold format -- '%s'. Please specify a decimal value between 0 and 1." "${1}")"
				;;
			esac
			if [ -z "${gap_threshold}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --gap-threshold is specified, a decimal threshold between 0 and 1 must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --gap-threshold is specified, a decimal threshold between 0 and 1 must be provided."
					;;
				*)
					gap_threshold="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
			awk -v number="${gap_threshold}" 'END { exit !( number !~ /[^0-9.]/ && number !~ /\..*\./ && number >= 0 && number <= 1) }' /dev/null || throw "$(printf "ERROR: Invalid gap threshold format -- '%s'. Please specify a decimal value between 0 and 1." "${gap_threshold}")"
		elif printf "%s" "${1}" | grep -q -E -- "^(-l)|(--l(e(n(g(t(h(-(t(h(r(e(s(h(o(l(d)?)?)?)?)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				length_threshold="${1#"${leader}"}"
				;;
			--length-threshold*)
				length_threshold="${1#--length-threshold}"
				;;
			--length-threshol*)
				length_threshold="${1#--length-threshol}"
				;;
			--length-thresho*)
				length_threshold="${1#--length-thresho}"
				;;
			--length-thresh*)
				length_threshold="${1#--length-thresh}"
				;;
			--length-thres*)
				length_threshold="${1#--length-thres}"
				;;
			--length-thre*)
				length_threshold="${1#--length-thre}"
				;;
			--length-thr*)
				length_threshold="${1#--length-thr}"
				;;
			--length-th*)
				length_threshold="${1#--length-th}"
				;;
			--length-t*)
				length_threshold="${1#--length-t}"
				;;
			--length-*)
				length_threshold="${1#--length-}"
				;;
			--length*)
				length_threshold="${1#--length}"
				;;
			--lengt*)
				length_threshold="${1#--lengt}"
				;;
			--leng*)
				length_threshold="${1#--leng}"
				;;
			--len*)
				length_threshold="${1#--len}"
				;;
			--le*)
				length_threshold="${1#--le}"
				;;
			--l*)
				length_threshold="${1#--l}"
				;;
			-l*)
				length_threshold="${1#-l}"
				;;
			*)
				throw "$(printf "ERROR: Invalid length threshold format -- '%s'. Please specify a decimal value between 0 and 1." "${1}")"
				;;
			esac
			if [ -z "${length_threshold}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --length-threshold is specified, a decimal threshold between 0 and 1 must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --length-threshold is specified, a decimal threshold between 0 and 1 must be provided."
					;;
				*)
					length_threshold="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
			awk -v number="${length_threshold}" 'END { exit !( number !~ /[^0-9.]/ && number !~ /\..*\./ && number >= 0 && number <= 1) }' /dev/null || throw "$(printf "ERROR: Invalid length threshold format -- '%s'. Please specify a decimal value between 0 and 1." "${length_threshold}")"
		elif printf "%s" "${1}" | grep -q -E -- "^(-t)|(--t(h(r(e(a(d(-(l(i(m(i(t)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				thread_limit="${1#"${leader}"}"
				;;
			--thread-limit*)
				thread_limit="${1#--thread-limit}"
				;;
			--thread-limi*)
				thread_limit="${1#--thread-limi}"
				;;
			--thread-lim*)
				thread_limit="${1#--thread-lim}"
				;;
			--thread-li*)
				thread_limit="${1#--thread-li}"
				;;
			--thread-l*)
				thread_limit="${1#--thread-l}"
				;;
			--thread-*)
				thread_limit="${1#--thread-}"
				;;
			--thread*)
				thread_limit="${1#--thread}"
				;;
			--thre*)
				thread_limit="${1#--thre}"
				;;
			--thr*)
				thread_limit="${1#--thr}"
				;;
			--th*)
				thread_limit="${1#--th}"
				;;
			--t*)
				thread_limit="${1#--t}"
				;;
			-t*)
				thread_limit="${1#-t}"
				;;
			*)
				throw "$(printf "ERROR: Invalid thread limit format -- '%s'. Please specify a positive integer value." "${1}")"
				;;
			esac
			if [ -z "${thread_limit}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --thread-limit is specified, an integer limit must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --thread-limit is specified, an integer limit must be provided."
					;;
				*)
					thread_limit="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
			awk -v number="${thread_limit}" 'END { exit !( number !~ /[^0-9]/ && number > 0) }' /dev/null || throw "$(printf "ERROR: Invalid thread limit format -- '%s'. Please specify a positive integer value." "${thread_limit}")"
		elif printf "%s" "${1}" | grep -q -E -- "^(-m)|(--m(e(m(o(r(y(-(l(i(m(i(t)?)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				memory_limit="${1#"${leader}"}"
				;;
			--memory-limit*)
				memory_limit="${1#--memory-limit}"
				;;
			--memory-limi*)
				memory_limit="${1#--memory-limi}"
				;;
			--memory-lim*)
				memory_limit="${1#--memory-lim}"
				;;
			--memory-li*)
				memory_limit="${1#--memory-li}"
				;;
			--memory-l*)
				memory_limit="${1#--memory-l}"
				;;
			--memory-*)
				memory_limit="${1#--memory-}"
				;;
			--memory*)
				memory_limit="${1#--memory}"
				;;
			--memor*)
				memory_limit="${1#--memor}"
				;;
			--memo*)
				memory_limit="${1#--memo}"
				;;
			--mem*)
				memory_limit="${1#--mem}"
				;;
			--me*)
				memory_limit="${1#--me}"
				;;
			--m*)
				memory_limit="${1#--m}"
				;;
			-m*)
				memory_limit="${1#-m}"
				;;
			*)
				throw "$(printf "ERROR: Invalid memory limit format -- '%s'. Please specify a positive integer value." "${1}")"
				;;
			esac
			if [ -z "${memory_limit}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --memory-limit is specified, an integer limit must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --memory-limit is specified, an integer limit must be provided."
					;;
				*)
					memory_limit="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
			awk -v number="${memory_limit}" 'END { exit !( number !~ /[^0-9]/ && number > 0) }' /dev/null || throw "$(printf "ERROR: Invalid memory limit format -- '%s'. Please specify a positive integer value." "${memory_limit}")"
		elif printf "%s" "${1}" | grep -q -E -- "^(-p)|(--p(a(r(a(l(l(e(l(i(s(m)?)?)?)?)?)?)?)?)?)?)" 2>/dev/null; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				parallelism="${1#"${leader}"}"
				;;
			--parallelism*)
				parallelism="${1#--parallelism}"
				;;
			--parallelis*)
				parallelism="${1#--parallelis}"
				;;
			--paralleli*)
				parallelism="${1#--paralleli}"
				;;
			--parallel*)
				parallelism="${1#--parallel}"
				;;
			--paralle*)
				parallelism="${1#--paralle}"
				;;
			--parall*)
				parallelism="${1#--parall}"
				;;
			--paral*)
				parallelism="${1#--paral}"
				;;
			--para*)
				parallelism="${1#--para}"
				;;
			--par*)
				parallelism="${1#--par}"
				;;
			--pa*)
				parallelism="${1#--pa}"
				;;
			--p*)
				parallelism="${1#--p}"
				;;
			-p*)
				parallelism="${1#-p}"
				;;
			*)
				throw "$(printf "ERROR: Invalid parallelism format -- '%s'. Please specify a positive integer value." "${1}")"
				;;
			esac
			if [ -z "${parallelism}" ]; then
				if [ -z "${2}" ]; then
					throw "ERROR: If --parallelism is specified, an integer limit must be provided."
				fi
				case "${2}" in
				-*)
					throw "ERROR: If --parallelism is specified, an integer limit must be provided."
					;;
				*)
					parallelism="${2}"
					shift 1
					;;
				esac
			fi
			shift 1
			awk -v number="${parallelism}" 'END { exit !( number !~ /[^0-9]/ && number > 0) }' /dev/null || throw "$(printf "ERROR: Invalid parallelism format -- '%s'. Please specify a positive integer value." "${parallelism}")"
		elif [ "${1}" = "--" ]; then
			shift 1
			break
		elif printf "%s" "${1}" | grep -q -E -- "^-.*" 2>/dev/null; then
			throw "$(printf "ERROR: invalid option -- '%s'" "${1}")"
		else
			break
		fi
	done

	if [ "${#}" -lt 1 ]; then
		throw "ERROR: An input file in FASTA format or directory thereof is required."
	fi

	# Debug logging control, set to 1 to enable
	verbose="${verbose:-0}"

	# Configuration of sequence identity, gap frequency, and length thresholds
	identity_threshold="${identity_threshold:-0.9}"
	gap_threshold="${gap_threshold:-0.5}"
	length_threshold="${length_threshold:-0.3}"

	# Determines how many FASTA files are processed simultaneously when receiving directory input
	parallelism="${parallelism:-"$(nproc --all)"}"

	# Determines memory limit in megabytes used during clustering
	memory_limit="${memory_limit:-4000}"

	# Determines the number of threads used during alignment
	thread_limit="${thread_limit:-1}"

	# Output and logging paths
	output_dir="${output_dir:-output}"
	work_dir="${output_dir}/work"
	log_dir="${work_dir}/logs"
	length_filtered_log="${log_dir}/length_filtered.log"
	clustered_log="${log_dir}/clustered.log"
	aligned_log="${log_dir}/aligned.log"
	completed_log="${log_dir}/completed.log"
	versions="${output_dir}/versions.yml"

	# Perform dependency checks and setup directories
	setup

	if [ -f "${1}" ]; then
		process_fasta "${1}"
	elif [ -d "${1}" ]; then
		dispatched_jobs=""
		trap 'cull_workers' EXIT HUP INT QUIT ABRT TERM # Culls worker processes if the main thread ends unexpectedly to prevent them from becoming zombies
		find "${1}" -maxdepth 1 -type f -name "*.fa*" -print | while read -r fasta; do
			while [ "$(printf "%s" "${dispatched_jobs}" | wc -w)" -ge "${parallelism}" ]; do
				active_jobs=""
				for job in $dispatched_jobs; do
					if kill -0 "${job}" 2>/dev/null; then
						active_jobs="${active_jobs} ${job}"
					fi
				done
				dispatched_jobs="${active_jobs}"
				sleep 1
			done
			process_fasta "${fasta}" &
			dispatched_jobs="${dispatched_jobs} ${!}"
		done
		wait
	else
		throw "ERROR: An input file in FASTA format or directory thereof is required."
	fi

	# Record software versions
	pipeline_completion
}

main "${@}"
